version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: app-backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:cached
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: app-frontend
    env_file: .env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0 --port 5173

  db:
    image: postgres:15
    container_name: app-db
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django -d django_dev"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 5s

volumes:
  postgres_data:
